### learn pandas by doing random exercises

In [3]:
# clears all the variable values previously set
# from IPython import get_ipython
# get_ipython().magic("reset -sf")

In [4]:
# numpy is good for multidimensional arrays and much more.
import numpy as np
# pandas is used for data manipulation and analysis
import pandas as pd

#from pandas_datareader import data as web #reads stock data
import matplotlib.pyplot as plt # plotting
import matplotlib.dates as mdates # styling dates
from toolz.utils import raises
%matplotlib notebook

import warnings
warnings.simplefilter("ignore")

## Numpy stuff

In [5]:
# arrays and stuff
just_a_list = [1,2,3,4]
nparray = np.array(just_a_list) # convert the list to a numpy array
nparray
type(nparray) # returns np.ndarray -> nd stands for n-dimensional

numpy.ndarray

### array in range

In [6]:
# create array from 0 to 4
nparray1 = np.arange(0,5)  # start, stop
nparray1

array([0, 1, 2, 3, 4])

In [7]:
# define a step
nparray3 = np.arange(0,11,2) ## start, stop, step
nparray3

array([ 0,  2,  4,  6,  8, 10])

### Matrices (or fancy name for 3D arrays, I guess?)

In [8]:
# create a 4 row matrix with 3 columns with all having the same value
matrice1 = np.zeros((4,3)) # fills the matrix in this order rows, columns
matrice1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### random matrices

In [9]:
# random values between 0 and 13 as a matrix with 4 rows and 3 columns
matrice2 = np.random.randint(0,13,(4,3)) # (value-range start,end,(row,column))
matrice2

array([[10,  5,  6],
       [10,  3,  5],
       [ 6,  9,  4],
       [ 0, 11,  5]])

### generate defined number of values in range

In [10]:
# generate 10 equally distanced values between 1 and 10
matrice3 = np.linspace(1,10,5) # good when I wannt to divide 100 in 15 chunks
matrice3_1 = np.linspace(1,10,5)
matrice3_1 = np.linspace(100,0,5)
print(matrice3, "\n", matrice3_1)
print("\n")
print(matrice3, "\n", matrice3_1)

[ 1.    3.25  5.5   7.75 10.  ] 
 [100.  75.  50.  25.   0.]


[ 1.    3.25  5.5   7.75 10.  ] 
 [100.  75.  50.  25.   0.]


### reshape arrays

In [11]:
# create array with 12 values
matrice4 = np.random.randint(0,50,12)
matrice4

array([ 9, 15, 45,  7, 31, 25, 23, 23, 12,  0, 22, 14])

In [12]:
# reshape to a 3 row 4 column array
matrice5 = matrice2.reshape(3,4) # var_new = var_call.reshape(row,col)
matrice5

array([[10,  5,  6, 10],
       [ 3,  5,  6,  9],
       [ 4,  0, 11,  5]])

In [13]:
# reshape into a 3d arraw with 3 blocks, 2 rows, 2 columns
# reshape differently, 2 blocks, 2 rows, 3 columns
matrice6 = matrice2.reshape(3,2,2) # reshape(blocks,row,col)
matrice6

array([[[10,  5],
        [ 6, 10]],

       [[ 3,  5],
        [ 6,  9]],

       [[ 4,  0],
        [11,  5]]])

In [14]:
# get the values in the 2nd block, 3rd row and last column
matrice6[0][1][1]

10

### filter arrays

In [15]:
# provide a boolean array where values are above 10
print(matrice2)
matrice2 > 10

[[10  5  6]
 [10  3  5]
 [ 6  9  4]
 [ 0 11  5]]


array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

In [16]:
# return an array with just values over 20
matrice2[matrice2 > 5] 

array([10,  6, 10,  6,  9, 11])

## basic basic stats

In [17]:
# mean, avg, median, std, var, maybe add some more later ?
eth_price = np.random.randint(90,4800,48) # buy 1 eth once a month
eth_price 
print("Avg price is: ", eth_price.mean().round(2)) #why is it so easy ? ffs
print("Min is:        ", eth_price.min())
print( "Max is:       ", eth_price.max())
print("Std is:       ", eth_price.std().round())
print("variance is:  ", eth_price.var().round())

Avg price is:  2366.35
Min is:         239
Max is:        4790
Std is:        1241.0
variance is:   1540425.0


### the seed function

In [18]:
np.random.seed(123) # SEED is the reason it stays the same
matrice7 = np.random.randint(0,50,10)
matrice7


array([45,  2, 28, 34, 38, 17, 19, 42, 22, 33])

## -------^_^------ PANDAS -------^_^------

###  read data from a CSV 


In [19]:
def get_data_from_csv(csv_file): 
    try:
        # Validate file extension
        if not csv_file.endswith('.csv'):
            raise ValueError('The file must be a csv file.')

        # Read the csv file
        df = pd.read_csv(csv_file)
    except FileNotFoundError:
        pass
    else:
        return df

pyrusdt_df = get_data_from_csv('csv_test_for_pandas.csv')
pyrusdt_df

experiment_id instrument OpenTS per 5 minutes  \
0    f3aef9c8-6bf0-4226-8478-a1505e87d281    PYRUSDT      2021-11-26 9:30   
1    f3aef9c8-6bf0-4226-8478-a1505e87d281    PYRUSDT      2021-11-26 9:50   
2    f3aef9c8-6bf0-4226-8478-a1505e87d281    PYRUSDT      2021-11-26 9:50   
3    f3aef9c8-6bf0-4226-8478-a1505e87d281    PYRUSDT     2021-11-26 10:10   
4    f3aef9c8-6bf0-4226-8478-a1505e87d281    PYRUSDT     2021-11-26 10:30   
..                                    ...        ...                  ...   
621  f3aef9c8-6bf0-4226-8478-a1505e87d281    PYRUSDT     2022-09-21 20:10   
622  f3aef9c8-6bf0-4226-8478-a1505e87d281    PYRUSDT     2022-09-21 23:10   
623  f3aef9c8-6bf0-4226-8478-a1505e87d281    PYRUSDT     2022-09-25 15:40   
624  f3aef9c8-6bf0-4226-8478-a1505e87d281    PYRUSDT      2022-09-28 4:20   
625  f3aef9c8-6bf0-4226-8478-a1505e87d281    PYRUSDT     2022-09-29 14:30   

    CloseTS per 5 minutes duration in hours duration in minutes  job_id  \
0         2021-11-26 9:40              0:10                  10     NaN   
1         2021-11-26 9:50              0:00                   0     NaN   
2        2021-11-26 10:00              0:10                  10     NaN   
3        2021-11-26 10:20              0:10                  10     NaN   
4        2021-11-26 10:40              0:10                  10     NaN   
..                    ...               ...                 ...     ...   
621      2022-09-21 20:30              0:20                  20     NaN   
622       2022-09-22 1:00              1:50                 110     NaN   
623      2022-09-25 16:10              0:30                  30     NaN   
624       2022-09-28 8:00              3:40                 220     NaN   
625      2022-09-29 16:40              2:10                 130     NaN   

     amount  lowest_v  highest_v  ...  total nr of trades  AVG trade duration  \
0     1,000    938.99    1030.00  ...               626.0                94.0   
1     1,029   1022.15    1060.10  ...                 NaN                 NaN   
2     1,059   1041.63    1091.09  ...                 NaN                 NaN   
3     1,090   1061.29    1106.21  ...                 NaN                 NaN   
4     1,087   1060.77    1119.23  ...                 NaN                 NaN   
..      ...       ...        ...  ...                 ...                 ...   
621  26,776  26755.86   27579.21  ...                 NaN                 NaN   
622  27,559  27013.34   27887.55  ...                 NaN                 NaN   
623  27,605  27341.21   28231.01  ...                 NaN                 NaN   
624  28,129  27933.88   28717.08  ...                 NaN                 NaN   
625  28,696  27638.58   28753.68  ...                 NaN                 NaN   

     AVG nov-dec  AVG jan-may  AVG june-oct  profitable trades  Losing trades  \
0           64.0         97.0         140.0              438.0          188.0   
1            NaN          NaN           NaN                NaN            NaN   
2            NaN          NaN           NaN                NaN            NaN   
3            NaN          NaN           NaN                NaN            NaN   
4            NaN          NaN           NaN                NaN            NaN   
..           ...          ...           ...                ...            ...   
621          NaN          NaN           NaN                NaN            NaN   
622          NaN          NaN           NaN                NaN            NaN   
623          NaN          NaN           NaN                NaN            NaN   
624          NaN          NaN           NaN                NaN            NaN   
625          NaN          NaN           NaN                NaN            NaN   

     Unnamed: 29  Unnamed: 30  Unnamed: 31  
0            NaN          NaN          NaN  
1            NaN          NaN          NaN  
2            NaN          NaN          NaN  
3     percentile          NaN          NaN  
4          -0.27          NaN  

###  read data from a XLS 



In [20]:
# define func that takes one argument( a csv file)
# we validate if the file is a csv format. if not, raise error
# the function then tries to read the csv file using the pandas.read_csv function
# if the csv is not found, an error is raised.
# otherwise the data is returned in a pandas dataframe
# call function and pass the csv file, storing the data in the desired variable

def get_data_from_excel_file(excel_file):
    try:
        #validate if file is excel format
        if not excel_file.endswith('.xlsx'):
            raise ValueError('the file must be of xlsx type.')

        # Read the csv file
        df = pd.read_excel(excel_file)
    except FileNotFoundError:
        pass
    else:
        return df

excel_df = get_data_from_excel_file('xls_test_for_pandas.xlsx')
excel_df



experiment_id instrument OpenTS per 5 minutes  \
0    f1679b0b-befb-4200-a58f-4991063a84f9   LINKUSDT  2022-06-16 04:40:00   
1    f1679b0b-befb-4200-a58f-4991063a84f9   AVAXUSDT  2022-06-16 12:05:00   
2    f1679b0b-befb-4200-a58f-4991063a84f9    ETHUSDT  2022-06-16 12:15:00   
3    f1679b0b-befb-4200-a58f-4991063a84f9   NEARUSDT  2022-06-16 12:20:00   
4    f1679b0b-befb-4200-a58f-4991063a84f9   ATOMUSDT  2022-06-16 12:20:00   
..                                    ...        ...                  ...   
161  f1679b0b-befb-4200-a58f-4991063a84f9   AVAXUSDT  2022-08-09 17:05:00   
162  f1679b0b-befb-4200-a58f-4991063a84f9    SOLUSDT  2022-08-09 17:05:00   
163  f1679b0b-befb-4200-a58f-4991063a84f9   NEARUSDT  2022-08-10 03:35:00   
164  f1679b0b-befb-4200-a58f-4991063a84f9   LINKUSDT  2022-08-10 03:35:00   
165  f1679b0b-befb-4200-a58f-4991063a84f9   ATOMUSDT  2022-08-10 03:40:00   

    CloseTS per 5 minutes trade duration  \
0     2022-06-16 18:05:00       13:25:00   
1     2022-06-16 22:05:00       10:00:00   
2     2022-06-17 04:40:00       16:25:00   
3     2022-06-16 18:25:00       06:05:00   
4     2022-06-17 08:30:00       20:10:00   
..                    ...            ...   
161   2022-08-10 00:25:00       07:20:00   
162   2022-08-10 11:50:00       18:45:00   
163   2022-08-10 08:00:00       04:25:00   
164   2022-08-10 11:50:00       08:15:00   
165   2022-08-10 10:40:00       07:00:00   

                                       job_id    amount  lowest_v  highest_v  \
0    8ad9ef080cb96ad2f5f4a2c0ce6d23156b01f0d7  1000.000   870.134   1007.671   
1    10234c1db8d56ed59bba267bdef7daf293a745d2  1000.000   951.007   1016.136   
2    c45240851a8fea459a8fbef51b702179228dff48  1000.000   925.255   1014.946   
3    aea3ddb65bbd095fa6fc5f252bff93e0ad738208  1000.000   950.938   1002.786   
4    cbd41990c604e1c26f4fdffede4fb8ee39b9ff45  1000.000   916.227   1002.216   
..                                        ...       ...       ...        ...   
161  10234c1db8d56ed59bba267bdef7daf293a745d2  1124.105  1122.017   1149.404   
162  036f9180e286e701d3bbafea7e23eb6c8671f20f  1140.005  1118.860   1163.728   
163  aea3ddb65bbd095fa6fc5f252bff93e0ad738208  1279.957  1264.347   1318.356   
164  8ad9ef080cb96ad2f5f4a2c0ce6d23156b01f0d7   878.520   863.704    889.208   
165  cbd41990c604e1c26f4fdffede4fb8ee39b9ff45  1083.201  1033.803   1083.473   

     profit_v  profit_p  max_DD  open_price  close_price  tp_p  TP reached  
0     -85.642    -8.564 -12.987       7.125        6.515     3      -8.564  
1      14.771     1.477  -4.899      16.582       16.827     3       1.477  
2     -31.212    -3.121  -7.474    1136.021     1100.564     3      -3.121  
3     -11.802    -1.180  -4.906       3.395        3.354     3      -1.180  
4     -38.535    -3.854  -8.377       6.745        6.485     3      -3.854  
..        ...       ...     ...         ...          ...   ...         ...  
161    24.023     2.137  -0.186      27.090       27.669     3       2.137  
162     2.004     0.176  -1.855      39.890       39.960     3       0.176  
163    37.410     2.923  -1.220       5.242        5.395     3       2.923  
164     0.348     0.040  -1.686       8.439        8.443     3       0.040  
165   -13.145    -1.214  -4.560      10.991       10.858     3      -1.214  

[166 rows x 16 columns]

###  read data from a HTML 



In [21]:
get_full_data_from_html = pd.read_html("https://en.wikipedia.org/wiki/Demographics_of_the_United_States")
get_full_data_from_html

[                    Demographics of the United States  \
 0   Population pyramid of the United States as of ...   
 1                                          Population   
 2                                             Density   
 3                                         Growth rate   
 4                                          Birth rate   
 5                                          Death rate   
 6                                     Life expectancy   
 7                                              • male   
 8                                            • female   
 9                                      Fertility rate   
 10                              Infant mortality rate   
 11                                 Net migration rate   
 12                                      Age structure   
 13                                     Under 18 years   
 14                                        18–44 years   
 15                                        45–64 years   
 16           

### read a column (us demographics)


In [22]:
# match searches found in tables
vital_statistics = pd.read_html("https://en.wikipedia.org/wiki/Demographics_of_the_United_States",match="Average population")[0]
vital_statistics

Unnamed: 0  Average population[76][30][31]  Live births[77]  \
0                       1935                       127250000          2377000   
1                       1936                       128053000          2355000   
2                       1937                       128825000          2413000   
3                       1938                       129825000          2496000   
4                       1939                       130880000          2466000   
..                       ...                             ...              ...   
82              2017[80][81]                       325122128          3855500   
83              2018[82][83]                       326838199          3791712   
84                      2019                       328329953          3747540   
85              2020[84][85]                       331501080          3613647   
86  2021[86][87][88][89][90]                       331893745          3664292   

     Deaths  Natural change  Crude birth rate (per 1,000)  \
0   1392752          984248                          18.7   
1   1479228          875772                          18.4   
2   1450427          962573                          18.7   
3   1381391         1114609                          19.2   
4   1387897         1078103                          18.8   
..      ...             ...                           ...   
82  2813503         1041997                          11.8   
83  2839205          952507                          11.6   
84  2854858          892682                          11.4   
85  3383729          229918                          10.9   
86  3464231          200061                          11.0   

    Crude death rate (per 1,000)[78]  Natural change (per 1,000)  \
0                               10.9                         7.7   
1                               11.5                         6.8   
2                               11.2                         7.5   
3                               10.6                         8.6   
4                               10.6                         8.2   
..                               ...                         ...   
82                               8.7                         3.1   
83                               8.7                         2.9   
84                               8.7                         2.7   
85                              10.2                         0.7   
86                              10.5                         0.5   

    Total fertility rate[fn 1][79]  
0                            2.190  
1                            2.150  
2                            2.170  
3                            2.220  
4                            2.170  
..                             ...  
82                           1.765  
83                           1.729  
84                           1.706  
85                           1.641  
86                           1.664  

[87 rows x 9 columns]

### replace spaces with column names


In [23]:
# replace spaces with column names // >>>>>>> this needs to be exercised more <<<<<<
vital_statistics.columns = [x.replace(' ', '_') for x in vital_statistics.columns]
vital_statistics

Unnamed:_0  Average_population[76][30][31]  Live_births[77]  \
0                       1935                       127250000          2377000   
1                       1936                       128053000          2355000   
2                       1937                       128825000          2413000   
3                       1938                       129825000          2496000   
4                       1939                       130880000          2466000   
..                       ...                             ...              ...   
82              2017[80][81]                       325122128          3855500   
83              2018[82][83]                       326838199          3791712   
84                      2019                       328329953          3747540   
85              2020[84][85]                       331501080          3613647   
86  2021[86][87][88][89][90]                       331893745          3664292   

     Deaths  Natural_change  Crude_birth_rate_(per_1,000)  \
0   1392752          984248                          18.7   
1   1479228          875772                          18.4   
2   1450427          962573                          18.7   
3   1381391         1114609                          19.2   
4   1387897         1078103                          18.8   
..      ...             ...                           ...   
82  2813503         1041997                          11.8   
83  2839205          952507                          11.6   
84  2854858          892682                          11.4   
85  3383729          229918                          10.9   
86  3464231          200061                          11.0   

    Crude_death_rate_(per_1,000)[78]  Natural_change_(per_1,000)  \
0                               10.9                         7.7   
1                               11.5                         6.8   
2                               11.2                         7.5   
3                               10.6                         8.6   
4                               10.6                         8.2   
..                               ...                         ...   
82                               8.7                         3.1   
83                               8.7                         2.9   
84                               8.7                         2.7   
85                              10.2                         0.7   
86                              10.5                         0.5   

    Total_fertility_rate[fn_1][79]  
0                            2.190  
1                            2.150  
2                            2.170  
3                            2.220  
4                            2.170  
..                             ...  
82                           1.765  
83                           1.729  
84                           1.706  
85                           1.641  
86                           1.664  

[87 rows x 9 columns]

### remove characters in columns ( rounded parentheses)


In [24]:
# remove parentheses and what's inside them <<<<<< needs repetition ! <<<<<<
vital_statistics.columns = vital_statistics.columns.str.replace(r"\(.*\)","")
vital_statistics

Unnamed:_0  Average_population[76][30][31]  Live_births[77]  \
0                       1935                       127250000          2377000   
1                       1936                       128053000          2355000   
2                       1937                       128825000          2413000   
3                       1938                       129825000          2496000   
4                       1939                       130880000          2466000   
..                       ...                             ...              ...   
82              2017[80][81]                       325122128          3855500   
83              2018[82][83]                       326838199          3791712   
84                      2019                       328329953          3747540   
85              2020[84][85]                       331501080          3613647   
86  2021[86][87][88][89][90]                       331893745          3664292   

     Deaths  Natural_change  Crude_birth_rate_  Crude_death_rate_[78]  \
0   1392752          984248               18.7                   10.9   
1   1479228          875772               18.4                   11.5   
2   1450427          962573               18.7                   11.2   
3   1381391         1114609               19.2                   10.6   
4   1387897         1078103               18.8                   10.6   
..      ...             ...                ...                    ...   
82  2813503         1041997               11.8                    8.7   
83  2839205          952507               11.6                    8.7   
84  2854858          892682               11.4                    8.7   
85  3383729          229918               10.9                   10.2   
86  3464231          200061               11.0                   10.5   

    Natural_change_  Total_fertility_rate[fn_1][79]  
0               7.7                           2.190  
1               6.8                           2.150  
2               7.5                           2.170  
3               8.6                           2.220  
4               8.2                           2.170  
..              ...                             ...  
82              3.1                           1.765  
83              2.9                           1.729  
84              2.7                           1.706  
85              0.7                           1.641  
86              0.5                           1.664  

[87 rows x 9 columns]

### remove characters in columns (squared parentheses)

In [25]:
# remove parentheses and what's inside them <<<<<< needs repetition ! <<<<<<
vital_statistics.columns = vital_statistics.columns.str.replace(r"\[.*\]","")
vital_statistics

Unnamed:_0  Average_population  Live_births   Deaths  \
0                       1935           127250000      2377000  1392752   
1                       1936           128053000      2355000  1479228   
2                       1937           128825000      2413000  1450427   
3                       1938           129825000      2496000  1381391   
4                       1939           130880000      2466000  1387897   
..                       ...                 ...          ...      ...   
82              2017[80][81]           325122128      3855500  2813503   
83              2018[82][83]           326838199      3791712  2839205   
84                      2019           328329953      3747540  2854858   
85              2020[84][85]           331501080      3613647  3383729   
86  2021[86][87][88][89][90]           331893745      3664292  3464231   

    Natural_change  Crude_birth_rate_  Crude_death_rate_  Natural_change_  \
0           984248               18.7               10.9              7.7   
1           875772               18.4               11.5              6.8   
2           962573               18.7               11.2              7.5   
3          1114609               19.2               10.6              8.6   
4          1078103               18.8               10.6              8.2   
..             ...                ...                ...              ...   
82         1041997               11.8                8.7              3.1   
83          952507               11.6                8.7              2.9   
84          892682               11.4                8.7              2.7   
85          229918               10.9               10.2              0.7   
86          200061               11.0               10.5              0.5   

    Total_fertility_rate  
0                  2.190  
1                  2.150  
2                  2.170  
3                  2.220  
4                  2.170  
..                   ...  
82                 1.765  
83                 1.729  
84                 1.706  
85                 1.641  
86                 1.664  

[87 rows x 9 columns]

### Rename Columns


In [26]:
vital_statistics = vital_statistics.rename(columns={'Crude_birth_rate_': 'Crude_birth_rate'})
vital_statistics

vital_statistics = vital_statistics.rename(columns={'Crude_death_rate_': 'Crude_death_rate'})
vital_statistics

vital_statistics = vital_statistics.rename(columns={'Natural_change_': 'Natural_change'})
vital_statistics

vital_statistics = vital_statistics.rename(columns={'Unnamed:_0': "Year"})
vital_statistics


Year  Average_population  Live_births   Deaths  \
0                       1935           127250000      2377000  1392752   
1                       1936           128053000      2355000  1479228   
2                       1937           128825000      2413000  1450427   
3                       1938           129825000      2496000  1381391   
4                       1939           130880000      2466000  1387897   
..                       ...                 ...          ...      ...   
82              2017[80][81]           325122128      3855500  2813503   
83              2018[82][83]           326838199      3791712  2839205   
84                      2019           328329953      3747540  2854858   
85              2020[84][85]           331501080      3613647  3383729   
86  2021[86][87][88][89][90]           331893745      3664292  3464231   

    Natural_change  Crude_birth_rate  Crude_death_rate  Natural_change  \
0           984248              18.7              10.9             7.7   
1           875772              18.4              11.5             6.8   
2           962573              18.7              11.2             7.5   
3          1114609              19.2              10.6             8.6   
4          1078103              18.8              10.6             8.2   
..             ...               ...               ...             ...   
82         1041997              11.8               8.7             3.1   
83          952507              11.6               8.7             2.9   
84          892682              11.4               8.7             2.7   
85          229918              10.9              10.2             0.7   
86          200061              11.0              10.5             0.5   

    Total_fertility_rate  
0                  2.190  
1                  2.150  
2                  2.170  
3                  2.220  
4                  2.170  
..                   ...  
82                 1.765  
83                 1.729  
84                 1.706  
85                 1.641  
86                 1.664  

[87 rows x 9 columns]

### Remove Characters in Columns

In [27]:
# look at previous column, rows #82 to #86. If I want to remove the parentheses, i'd do it like this:
# df.X = df.X.str.replace(r"\[.*\]","") where X is the desired column, in my case Year
# also, in my case I wanted to remove the references which are [] with numbers in them
vital_statistics.Year = vital_statistics.Year.str.replace(r"\[.*\]","")
vital_statistics

Year  Average_population  Live_births   Deaths  Natural_change  \
0   1935           127250000      2377000  1392752          984248   
1   1936           128053000      2355000  1479228          875772   
2   1937           128825000      2413000  1450427          962573   
3   1938           129825000      2496000  1381391         1114609   
4   1939           130880000      2466000  1387897         1078103   
..   ...                 ...          ...      ...             ...   
82  2017           325122128      3855500  2813503         1041997   
83  2018           326838199      3791712  2839205          952507   
84  2019           328329953      3747540  2854858          892682   
85  2020           331501080      3613647  3383729          229918   
86  2021           331893745      3664292  3464231          200061   

    Crude_birth_rate  Crude_death_rate  Natural_change  Total_fertility_rate  
0               18.7              10.9             7.7                 2.190  
1               18.4              11.5             6.8                 2.150  
2               18.7              11.2             7.5                 2.170  
3               19.2              10.6             8.6                 2.220  
4               18.8              10.6             8.2                 2.170  
..               ...               ...             ...                   ...  
82              11.8               8.7             3.1                 1.765  
83              11.6               8.7             2.9                 1.729  
84              11.4               8.7             2.7                 1.706  
85              10.9              10.2             0.7                 1.641  
86              11.0              10.5             0.5                 1.664  

[87 rows x 9 columns]

### selecting a particular column

In [28]:
vital_statistics.Average_population  # df.column_name
vital_statistics['Average_population'] # works the same

0     127250000
1     128053000
2     128825000
3     129825000
4     130880000
        ...    
82    325122128
83    326838199
84    328329953
85    331501080
86    331893745
Name: Average_population, Length: 87, dtype: int64

### Make a Column an Index

In [29]:
# good when you don't want the standard index, but a different desired column (like Year in this ex)
vital_statistics.set_index('Year', inplace=True)
vital_statistics

Average_population  Live_births   Deaths  Natural_change  \
Year                                                             
1935           127250000      2377000  1392752          984248   
1936           128053000      2355000  1479228          875772   
1937           128825000      2413000  1450427          962573   
1938           129825000      2496000  1381391         1114609   
1939           130880000      2466000  1387897         1078103   
...                  ...          ...      ...             ...   
2017           325122128      3855500  2813503         1041997   
2018           326838199      3791712  2839205          952507   
2019           328329953      3747540  2854858          892682   
2020           331501080      3613647  3383729          229918   
2021           331893745      3664292  3464231          200061   

      Crude_birth_rate  Crude_death_rate  Natural_change  Total_fertility_rate  
Year                                                                            
1935              18.7              10.9             7.7                 2.190  
1936              18.4              11.5             6.8                 2.150  
1937              18.7              11.2             7.5                 2.170  
1938              19.2              10.6             8.6                 2.220  
1939              18.8              10.6             8.2                 2.170  
...                ...               ...             ...                   ...  
2017              11.8               8.7             3.1                 1.765  
2018              11.6               8.7             2.9                 1.729  
2019              11.4               8.7             2.7                 1.706  
2020              10.9              10.2             0.7                 1.641  
2021              11.0              10.5             0.5                 1.664  

[87 rows x 8 columns]

In [30]:
# vital_statistics.reset_index() ## in case I want to revert to the standard index
# vital_statistics

### Grab Data from Multiple Columns


In [31]:
# var = list of lists
vital_statistics[['Live_births','Deaths']]

Live_births   Deaths
Year                      
1935      2377000  1392752
1936      2355000  1479228
1937      2413000  1450427
1938      2496000  1381391
1939      2466000  1387897
...           ...      ...
2017      3855500  2813503
2018      3791712  2839205
2019      3747540  2854858
2020      3613647  3383729
2021      3664292  3464231

[87 rows x 2 columns]

### Grab a Row


In [32]:
# # these would work if the index would off remained the standard one.
# vital_statistics.loc[0]  ## only show a particular row. It's display is confusing though.
# vital_statistics.loc[[0,1]] # here we have two rows, first and second
vital_statistics.loc['2021']

Average_population      3.318937e+08
Live_births             3.664292e+06
Deaths                  3.464231e+06
Natural_change          2.000610e+05
Crude_birth_rate        1.100000e+01
Crude_death_rate        1.050000e+01
Natural_change          5.000000e-01
Total_fertility_rate    1.664000e+00
Name: 2021, dtype: float64

In [33]:
vital_statistics.iloc[86]  # row by index loc

Average_population      3.318937e+08
Live_births             3.664292e+06
Deaths                  3.464231e+06
Natural_change          2.000610e+05
Crude_birth_rate        1.100000e+01
Crude_death_rate        1.050000e+01
Natural_change          5.000000e-01
Total_fertility_rate    1.664000e+00
Name: 2021, dtype: float64

### Add a Column


In [34]:
vital_statistics['Pop_Growth'] = vital_statistics['Live_births'] - vital_statistics['Deaths']
vital_statistics  # same with Natural change

Average_population  Live_births   Deaths  Natural_change  \
Year                                                             
1935           127250000      2377000  1392752          984248   
1936           128053000      2355000  1479228          875772   
1937           128825000      2413000  1450427          962573   
1938           129825000      2496000  1381391         1114609   
1939           130880000      2466000  1387897         1078103   
...                  ...          ...      ...             ...   
2017           325122128      3855500  2813503         1041997   
2018           326838199      3791712  2839205          952507   
2019           328329953      3747540  2854858          892682   
2020           331501080      3613647  3383729          229918   
2021           331893745      3664292  3464231          200061   

      Crude_birth_rate  Crude_death_rate  Natural_change  \
Year                                                       
1935              18.7              10.9             7.7   
1936              18.4              11.5             6.8   
1937              18.7              11.2             7.5   
1938              19.2              10.6             8.6   
1939              18.8              10.6             8.2   
...                ...               ...             ...   
2017              11.8               8.7             3.1   
2018              11.6               8.7             2.9   
2019              11.4               8.7             2.7   
2020              10.9              10.2             0.7   
2021              11.0              10.5             0.5   

      Total_fertility_rate  Pop_Growth  
Year                                    
1935                 2.190      984248  
1936                 2.150      875772  
1937                 2.170      962573  
1938                 2.220     1114609  
1939                 2.170     1078103  
...                    ...         ...  
2017                 1.765     1041997  
2018                 1.729      952507  
2019                 1.706      892682  
2020                 1.641      229918  
2021                 1.664      200061  

[87 rows x 9 columns]

### Delete Column


In [35]:
vital_statistics.drop('Pop_Growth', axis=1, inplace=True)  # drops desired column
vital_statistics

Average_population  Live_births   Deaths  Natural_change  \
Year                                                             
1935           127250000      2377000  1392752          984248   
1936           128053000      2355000  1479228          875772   
1937           128825000      2413000  1450427          962573   
1938           129825000      2496000  1381391         1114609   
1939           130880000      2466000  1387897         1078103   
...                  ...          ...      ...             ...   
2017           325122128      3855500  2813503         1041997   
2018           326838199      3791712  2839205          952507   
2019           328329953      3747540  2854858          892682   
2020           331501080      3613647  3383729          229918   
2021           331893745      3664292  3464231          200061   

      Crude_birth_rate  Crude_death_rate  Natural_change  Total_fertility_rate  
Year                                                                            
1935              18.7              10.9             7.7                 2.190  
1936              18.4              11.5             6.8                 2.150  
1937              18.7              11.2             7.5                 2.170  
1938              19.2              10.6             8.6                 2.220  
1939              18.8              10.6             8.2                 2.170  
...                ...               ...             ...                   ...  
2017              11.8               8.7             3.1                 1.765  
2018              11.6               8.7             2.9                 1.729  
2019              11.4               8.7             2.7                 1.706  
2020              10.9              10.2             0.7                 1.641  
2021              11.0              10.5             0.5                 1.664  

[87 rows x 8 columns]

In [36]:
vital_statistics_test = vital_statistics ## some variations for other settings
vital_statistics_test

Average_population  Live_births   Deaths  Natural_change  \
Year                                                             
1935           127250000      2377000  1392752          984248   
1936           128053000      2355000  1479228          875772   
1937           128825000      2413000  1450427          962573   
1938           129825000      2496000  1381391         1114609   
1939           130880000      2466000  1387897         1078103   
...                  ...          ...      ...             ...   
2017           325122128      3855500  2813503         1041997   
2018           326838199      3791712  2839205          952507   
2019           328329953      3747540  2854858          892682   
2020           331501080      3613647  3383729          229918   
2021           331893745      3664292  3464231          200061   

      Crude_birth_rate  Crude_death_rate  Natural_change  Total_fertility_rate  
Year                                                                            
1935              18.7              10.9             7.7                 2.190  
1936              18.4              11.5             6.8                 2.150  
1937              18.7              11.2             7.5                 2.170  
1938              19.2              10.6             8.6                 2.220  
1939              18.8              10.6             8.2                 2.170  
...                ...               ...             ...                   ...  
2017              11.8               8.7             3.1                 1.765  
2018              11.6               8.7             2.9                 1.729  
2019              11.4               8.7             2.7                 1.706  
2020              10.9              10.2             0.7                 1.641  
2021              11.0              10.5             0.5                 1.664  

[87 rows x 8 columns]

### Delete a Row


In [37]:
vital_statistics.drop('1935',axis=0, inplace=True)
vital_statistics

Average_population  Live_births   Deaths  Natural_change  \
Year                                                             
1936           128053000      2355000  1479228          875772   
1937           128825000      2413000  1450427          962573   
1938           129825000      2496000  1381391         1114609   
1939           130880000      2466000  1387897         1078103   
1940           131930000      2559000  1417269         1142000   
...                  ...          ...      ...             ...   
2017           325122128      3855500  2813503         1041997   
2018           326838199      3791712  2839205          952507   
2019           328329953      3747540  2854858          892682   
2020           331501080      3613647  3383729          229918   
2021           331893745      3664292  3464231          200061   

      Crude_birth_rate  Crude_death_rate  Natural_change  Total_fertility_rate  
Year                                                                            
1936              18.4              11.5             6.8                 2.150  
1937              18.7              11.2             7.5                 2.170  
1938              19.2              10.6             8.6                 2.220  
1939              18.8              10.6             8.2                 2.170  
1940              19.4              10.8             8.7                 2.301  
...                ...               ...             ...                   ...  
2017              11.8               8.7             3.1                 1.765  
2018              11.6               8.7             2.9                 1.729  
2019              11.4               8.7             2.7                 1.706  
2020              10.9              10.2             0.7                 1.641  
2021              11.0              10.5             0.5                 1.664  

[86 rows x 8 columns]


## --- Manipulating other data - Countries by GDP ---



In [38]:
countries_by_gdp = pd.read_html("https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)")[2]
countries_by_gdp


Country/Territory UN Region IMF[1][13]            World Bank[14]  \
    Country/Territory UN Region   Estimate       Year       Estimate   
0               World         —  101560901       2022       96100091   
1       United States  Americas   25035164       2022       22996100   
2               China      Asia   18321197  [n 1]2022       17734063   
3               Japan      Asia    4300621       2022        4937422   
4             Germany    Europe    4031149       2022        4223116   
..                ...       ...        ...        ...            ...   
212             Palau   Oceania        226       2022            258   
213          Kiribati   Oceania        207       2022            181   
214             Nauru   Oceania        134       2022            133   
215        Montserrat  Americas          —          —              —   
216            Tuvalu   Oceania         64       2022             63   

               United Nations[15]             
          Year           Estimate       Year  
0         2021           85328323       2020  
1         2021           20893746       2020  
2    [n 3]2021           14722801  [n 1]2020  
3         2021            5057759       2020  
4         2021            3846414       2020  
..         ...                ...        ...  
212       2020                264       2020  
213       2020                181       2020  
214       2021                135       2020  
215          —                 68       2020  
216       2021                 55       2020  

[217 rows x 8 columns]

In [39]:
for col in countries_by_gdp.columns: # iterate through columns top-dowm left right
    print(col)

('Country/Territory', 'Country/Territory')
('UN Region', 'UN Region')
('IMF[1][13]', 'Estimate')
('IMF[1][13]', 'Year')
('World Bank[14]', 'Estimate')
('World Bank[14]', 'Year')
('United Nations[15]', 'Estimate')
('United Nations[15]', 'Year')


In [40]:
# Delete a level of a multilevel column name
countries_by_gdp.columns = countries_by_gdp.columns.droplevel()
countries_by_gdp

Country/Territory UN Region   Estimate       Year  Estimate       Year  \
0               World         —  101560901       2022  96100091       2021   
1       United States  Americas   25035164       2022  22996100       2021   
2               China      Asia   18321197  [n 1]2022  17734063  [n 3]2021   
3               Japan      Asia    4300621       2022   4937422       2021   
4             Germany    Europe    4031149       2022   4223116       2021   
..                ...       ...        ...        ...       ...        ...   
212             Palau   Oceania        226       2022       258       2020   
213          Kiribati   Oceania        207       2022       181       2020   
214             Nauru   Oceania        134       2022       133       2021   
215        Montserrat  Americas          —          —         —          —   
216            Tuvalu   Oceania         64       2022        63       2021   

     Estimate       Year  
0    85328323       2020  
1    20893746       2020  
2    14722801  [n 1]2020  
3     5057759       2020  
4     3846414       2020  
..        ...        ...  
212       264       2020  
213       181       2020  
214       135       2020  
215        68       2020  
216        55       2020  

[217 rows x 8 columns]

In [41]:
# Keep only columns if they haven't used the same name prior
countries_by_gdp = countries_by_gdp.loc[:,~countries_by_gdp.columns.duplicated()]
countries_by_gdp

Country/Territory UN Region   Estimate       Year
0               World         —  101560901       2022
1       United States  Americas   25035164       2022
2               China      Asia   18321197  [n 1]2022
3               Japan      Asia    4300621       2022
4             Germany    Europe    4031149       2022
..                ...       ...        ...        ...
212             Palau   Oceania        226       2022
213          Kiribati   Oceania        207       2022
214             Nauru   Oceania        134       2022
215        Montserrat  Americas          —          —
216            Tuvalu   Oceania         64       2022

[217 rows x 4 columns]

### More Ways of Messing with Data
